### ISSUE TITLE
Stranka bez dat

### ISSUE THREAD

**Issue by oldastar** [netique/R_comparison#2]
https://netique.shinyapps.io/R_comparison/

An error has occurred. Check your logs or contact the app author for clarification.
Time series lag (in days)

**Comment by netique** [comment]
Thanks for reporting! This very issue is now solved in https://github.com/netique/R_comparison/commit/bbe575420b2b2459e557785e89000a0f3eee099f, but many are left to be tackled... Everything is due to JSON API v2 removal at MZCR side. Hope to implement v3 API soon, but it is way too limited because of DDoS measures.
